### ISSUE TITLE
load error

### ISSUE THREAD

**Issue by kp9589kp** [JoinedSenses/SM-SuperSprayHandler#12]
i keep getting a load error and im not sure why, only thing i can think of is im doing the SQL part wrong? im extremely new to this so the "coding" part(s) get me sometimes lol. do i copy both the " MySql" and "SqLite" and do i change anything in them when i put them into my database.cfg?

**Comment by kp9589kp** [comment]
![Screenshot 2024-03-26 203215](https://github.com/JoinedSenses/SM-SuperSprayHandler/assets/164273729/88de9c48-f751-406d-86d5-18bbccad5492)

**Comment by JoinedSenses** [comment]
Check addons/sourcemod/logs/ for error log as the message explains in your screen shot. It will give more information about what is going wrong. For mysql/sqlite, you only choose one. if you have a dedicated database set up that can be connected to, you would use mysql and plug in the connection information. otherwise just use sqlite config with no modifications to it.

**Comment by kp9589kp** [comment]
![Screenshot 2024-03-26 224308](https://github.com/JoinedSenses/SM-SuperSprayHandler/assets/164273729/41bad9cc-7637-4510-b6f3-f982f6d3d3ba)
![Screenshot 2024-03-26 224122](https://github.com/JoinedSenses/SM-SuperSprayHandler/assets/164273729/8f1cd73d-00e6-49c1-80d3-bde472062350)
my server is through PingPerfect, not sure if that effects which SQL i would use?

**Comment by kp9589kp** [comment]
after taking those screen shots and rejoining my server it seems to be working now, thanks for the help
